//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetDev.WCF.Client
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Msg", Namespace="http://schemas.datacontract.org/2004/07/ProjetDev.WCF.CommunicationParameters")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class Msg : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AppVersionField;
        
        private object[] DataField;
        
        private string InfoField;
        
        private string OperationNameField;
        
        private string OperationTypeField;
        
        private string OperationVersionField;
        
        private bool StatutOpField;
        
        private string TokenAppField;
        
        private string TokenUserField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersion
        {
            get
            {
                return this.AppVersionField;
            }
            set
            {
                this.AppVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName
        {
            get
            {
                return this.OperationNameField;
            }
            set
            {
                this.OperationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationType
        {
            get
            {
                return this.OperationTypeField;
            }
            set
            {
                this.OperationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationVersion
        {
            get
            {
                return this.OperationVersionField;
            }
            set
            {
                this.OperationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StatutOp
        {
            get
            {
                return this.StatutOpField;
            }
            set
            {
                this.StatutOpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenApp
        {
            get
            {
                return this.TokenAppField;
            }
            set
            {
                this.TokenAppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TokenUser
        {
            get
            {
                return this.TokenUserField;
            }
            set
            {
                this.TokenUserField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ProjetDev.WCF.Service", ConfigurationName="IRequestService")]
public interface IRequestService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ProjetDev.WCF.Service/IRequestService/Request", ReplyAction="http://ProjetDev.WCF.Service/IRequestService/RequestResponse")]
    ProjetDev.WCF.CommunicationParameters.Msg Request(ProjetDev.WCF.CommunicationParameters.Msg message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://ProjetDev.WCF.Service/IRequestService/Request", ReplyAction="http://ProjetDev.WCF.Service/IRequestService/RequestResponse")]
    System.Threading.Tasks.Task<ProjetDev.WCF.CommunicationParameters.Msg> RequestAsync(ProjetDev.WCF.CommunicationParameters.Msg message);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IRequestServiceChannel : IRequestService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RequestServiceClient : System.ServiceModel.ClientBase<IRequestService>, IRequestService
{
    
    public RequestServiceClient()
    {
    }
    
    public RequestServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public ProjetDev.WCF.CommunicationParameters.Msg Request(ProjetDev.WCF.CommunicationParameters.Msg message)
    {
        return base.Channel.Request(message);
    }
    
    public System.Threading.Tasks.Task<ProjetDev.WCF.CommunicationParameters.Msg> RequestAsync(ProjetDev.WCF.CommunicationParameters.Msg message)
    {
        return base.Channel.RequestAsync(message);
    }
}
